In [1]:
print("Jupyter is working!")

Jupyter is working!

In [2]:
import numpy as np
import pandas as pd

In [3]:
df=pd.read_csv("../data/vehicles.csv", nrows=50000)

In [4]:
df.head()

,id,url,region,region_url,price,year,manufacturer,model,condition,cylinders,...,size,type,paint_color,image_url,description,county,state,lat,long,posting_date
0,7222695916,https://prescott.craigslist.org/cto/d/prescott...,prescott,https://prescott.craigslist.org,6000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,az,NaN,NaN,NaN
1,7218891961,https://fayar.craigslist.org/ctd/d/bentonville...,fayetteville,https://fayar.craigslist.org,11900,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,ar,NaN,NaN,NaN
2,7221797935,https://keys.craigslist.org/cto/d/summerland-k...,florida keys,https://keys.craigslist.org,21000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,fl,NaN,NaN,NaN
3,7222270760,https://worcester.craigslist.org/cto/d/west-br...,worcester / central MA,https://worcester.craigslist.org,1500,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,ma,NaN,NaN,NaN
4,7210384030,https://greensboro.craigslist.org/cto/d/trinit...,greensboro,https://greensboro.craigslist.org,4900,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,nc,NaN,NaN,NaN

In [5]:
# shape
df.shape

(50000, 26)

In [6]:
# columns
df.columns

Index(['id', 'url', 'region', 'region_url', 'price', 'year', 'manufacturer',
       'model', 'condition', 'cylinders', 'fuel', 'odometer', 'title_status',
       'transmission', 'VIN', 'drive', 'size', 'type', 'paint_color',
       'image_url', 'description', 'county', 'state', 'lat', 'long',
       'posting_date'],
      dtype='str')

In [7]:
# data types
df.dtypes

id                int64
url                 str
region              str
region_url          str
price             int64
year            float64
manufacturer        str
model               str
condition           str
cylinders           str
fuel                str
odometer        float64
title_status        str
transmission        str
VIN                 str
drive               str
size                str
type                str
paint_color         str
image_url           str
description         str
county          float64
state               str
lat             float64
long            float64
posting_date        str
dtype: object

In [8]:
# basic information
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 26 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            50000 non-null  int64
 1   url           50000 non-null  str
 2   region        50000 non-null  str
 3   region_url    50000 non-null  str
 4   price         50000 non-null  int64
 5   year          49774 non-null  float64
 6   manufacturer  47796 non-null  str
 7   model         49256 non-null  str
 8   condition     30335 non-null  str
 9   cylinders     30209 non-null  str
 10  fuel          49794 non-null  str
 11  odometer      49073 non-null  float64
 12  title_status  48928 non-null  str
 13  transmission  49802 non-null  str
 14  VIN           31348 non-null  str
 15  drive         34378 non-null  str
 16  size          13270 non-null  str
 17  type          39366 non-null  str
 18  paint_color   34387 non-null  str
 19  image_url     49971 non-null  str
 20  description   49970 non-null  str
 21  county        0 non-null      float64
 22  state         50000 non-null  str
 23  lat           49852 non-null  float64
 24  long          49852 non-null  float64
 25  posting_date  49971 non-null  str
dtypes: float64(5), int64(2), str(19)
memory usage: 9.9 MB

In [9]:
# calculate missing values

df.isnull().sum()

id                  0
url                 0
region              0
region_url          0
price               0
year              226
manufacturer     2204
model             744
condition       19665
cylinders       19791
fuel              206
odometer          927
title_status     1072
transmission      198
VIN             18652
drive           15622
size            36730
type            10634
paint_color     15613
image_url          29
description        30
county          50000
state               0
lat               148
long              148
posting_date       29
dtype: int64

In [10]:
# percentage of each missing data in a cloumn

missing=df.isnull().sum()

missing_percentage=(missing/len(df))*100

missing_report=pd.DataFrame({
  "Missing Values": missing,
   "Missing Percentage": missing_percentage 
})

print(missing_report)

              Missing Values  Missing Percentage
id                         0               0.000
url                        0               0.000
region                     0               0.000
region_url                 0               0.000
price                      0               0.000
year                     226               0.452
manufacturer            2204               4.408
model                    744               1.488
condition              19665              39.330
cylinders              19791              39.582
fuel                     206               0.412
odometer                 927               1.854
title_status            1072               2.144
transmission             198               0.396
VIN                    18652              37.304
drive                  15622              31.244
size                   36730              73.460
type                   10634              21.268
paint_color            15613              31.226
image_url                 29               0.058
description               30               0.060
county                 50000             100.000
state                      0               0.000
lat                      148               0.296
long                     148               0.296
posting_date              29               0.058

In [11]:
#  check if all 50000 values are missing
df["county"].isnull().sum()

np.int64(50000)

In [12]:
# remove the county column because all the data is missing

df=df.drop(columns=["county"])

In [13]:
# check if the column county  was removed correctly

df.shape

(50000, 25)

In [14]:
# current situation after removing county
df.isnull().sum()

id                  0
url                 0
region              0
region_url          0
price               0
year              226
manufacturer     2204
model             744
condition       19665
cylinders       19791
fuel              206
odometer          927
title_status     1072
transmission      198
VIN             18652
drive           15622
size            36730
type            10634
paint_color     15613
image_url          29
description        30
state               0
lat               148
long              148
posting_date       29
dtype: int64

In [15]:
missing = df.isnull().sum()

missing_percentage = (missing / len(df)) * 100

missing_report = pd.DataFrame({
    "Missing Values": missing,
    "Missing Percentage": missing_percentage
})

missing_report

              Missing Values  Missing Percentage
id                         0               0.000
url                        0               0.000
region                     0               0.000
region_url                 0               0.000
price                      0               0.000
year                     226               0.452
manufacturer            2204               4.408
model                    744               1.488
condition              19665              39.330
cylinders              19791              39.582
fuel                     206               0.412
odometer                 927               1.854
title_status            1072               2.144
transmission             198               0.396
VIN                    18652              37.304
drive                  15622              31.244
size                   36730              73.460
type                   10634              21.268
paint_color            15613              31.226
image_url                 29               0.058
description               30               0.060
state                      0               0.000
lat                      148               0.296
long                     148               0.296
posting_date              29               0.058

In [16]:
# describe

df[["year", "odometer", "lat", "long"]].describe()

               year      odometer           lat          long
count  49774.000000  4.907300e+04  49852.000000  49852.000000
mean    2011.174207  9.684942e+04     37.102654   -113.689079
std       10.343847  2.823090e+05      7.135848     15.724375
min     1900.000000  0.000000e+00    -81.838232   -158.599600
25%     2008.000000  3.456300e+04     33.745144   -120.989395
50%     2014.000000  7.901500e+04     34.571326   -117.731620
75%     2017.000000  1.260850e+05     37.774100   -110.960560
max     2022.000000  1.000000e+07     82.390818    173.885502

In [17]:
df[["lat","long"]].isnull().sum()

lat     148
long    148
dtype: int64

In [18]:
# check how many rows have both lat and long missing
df[["lat","long"]].isnull().all(axis=1).sum()

np.int64(148)

In [19]:
# check if rows contain only one location cordinate

df[["lat","long"]].isnull().sum()

lat     148
long    148
dtype: int64

In [20]:
# remove rows with missing lat and long
df.dropna(subset=["lat", "long"])

,id,url,region,region_url,price,year,manufacturer,model,condition,cylinders,...,drive,size,type,paint_color,image_url,description,state,lat,long,posting_date
27,7316814884,https://auburn.craigslist.org/ctd/d/auburn-uni...,auburn,https://auburn.craigslist.org,33590,2014.0,gmc,sierra 1500 crew cab slt,good,8 cylinders,...,NaN,NaN,pickup,white,https://images.craigslist.org/00R0R_lwWjXSEWNa...,Carvana is the safer way to buy a car During t...,al,32.590000,-85.480000,2021-05-04T12:31:18-0500
28,7316814758,https://auburn.craigslist.org/ctd/d/auburn-uni...,auburn,https://auburn.craigslist.org,22590,2010.0,chevrolet,silverado 1500,good,8 cylinders,...,NaN,NaN,pickup,blue,https://images.craigslist.org/00R0R_lwWjXSEWNa...,Carvana is the safer way to buy a car During t...,al,32.590000,-85.480000,2021-05-04T12:31:08-0500
29,7316814989,https://auburn.craigslist.org/ctd/d/auburn-uni...,auburn,https://auburn.craigslist.org,39590,2020.0,chevrolet,silverado 1500 crew,good,8 cylinders,...,NaN,NaN,pickup,red,https://images.craigslist.org/01212_jjirIWa0y0...,Carvana is the safer way to buy a car During t...,al,32.590000,-85.480000,2021-05-04T12:31:25-0500
30,7316743432,https://auburn.craigslist.org/ctd/d/auburn-uni...,auburn,https://auburn.craigslist.org,30990,2017.0,toyota,tundra double cab sr,good,8 cylinders,...,NaN,NaN,pickup,red,https://images.craigslist.org/00x0x_1y9kIOzGCF...,Carvana is the safer way to buy a car During t...,al,32.590000,-85.480000,2021-05-04T10:41:31-0500
31,7316356412,https://auburn.craigslist.org/cto/d/auburn-uni...,auburn,https://auburn.craigslist.org,15000,2013.0,ford,f-150 xlt,excellent,6 cylinders,...,rwd,full-size,truck,black,https://images.craigslist.org/00404_l4loxHvdQe...,2013 F-150 XLT V6 4 Door. Good condition. Leve...,al,32.592000,-85.518900,2021-05-03T14:02:03-0500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,7313129682,https://reno.craigslist.org/ctd/d/reno-2017-ni...,reno / tahoe,https://reno.craigslist.org,15990,2017.0,nissan,altima 2.5 sv,excellent,4 cylinders,...,NaN,NaN,sedan,NaN,https://images.craigslist.org/00R0R_AniUUmB0Wk...,"2017 Nissan Altima 2.5 SV Sedan 62,029 $255/mo...",ca,39.495568,-119.789546,2021-04-26T17:30:35-0700
49996,7313125262,https://reno.craigslist.org/ctd/d/reno-2012-au...,reno / tahoe,https://reno.craigslist.org,16990,2012.0,audi,q5 3.2l premium plus,excellent,6 cylinders,...,4wd,NaN,SUV,NaN,https://images.craigslist.org/00505_e5b1sfIeui...,"2012 Audi Q5 3.2L Premium Plus SUV 71,945 $272...",ca,39.495568,-119.789546,2021-04-26T17:20:01-0700
49997,7313122554,https://reno.craigslist.org/ctd/d/reno-2020-je...,reno / tahoe,https://reno.craigslist.org,0,2020.0,jeep,wrangler,NaN,NaN,...,4wd,NaN,SUV,blue,https://images.craigslist.org/00X0X_4Xe2JBmRvK...,2020 Jeep Wrangler Unlimited Willys Offere...,ca,39.491150,-119.790321,2021-04-26T17:13:40-0700
49998,7313117031,https://reno.craigslist.org/ctd/d/reno-2013-bm...,reno / tahoe,https://reno.craigslist.org,18990,2013.0,bmw,x5 xdrive35i premium,excellent,6 cylinders,...,4wd,NaN,SUV,NaN,https://images.craigslist.org/01313_1eWfroS7ij...,2013 BMW X5 xDrive35i Premium xDrive35i Premiu...,ca,39.495568,-119.789546,2021-04-26T17:00:21-0700
49999,7313110339,https://reno.craigslist.org/cto/d/reno-2010-su...,reno / tahoe,https://reno.craigslist.org,9000,2010.0,subaru,outback,good,4 cylinders,...,4wd,compact,NaN,grey,https://images.craigslist.org/00y0y_a4vhCOjMOu...,"2010 Subaru Outback Pzev 131,000 miles $9,000 ...",ca,39.497200,-119.776400,2021-04-26T16:44:20-0700

In [21]:
# check the count of missing values in year and odometer
df[["year", "odometer"]].isnull().sum()

year        226
odometer    927
dtype: int64

In [22]:
#replace the missing values with median

df["year"]=df["year"].fillna(df["year"].median())

df["odometer"]=df["odometer"].fillna(df["odometer"].median())

In [23]:
df[["year","odometer"]].isnull().sum()

year        0
odometer    0
dtype: int64

In [24]:
# checking the remaining missing values
df.isnull().sum()

id                  0
url                 0
region              0
region_url          0
price               0
year                0
manufacturer     2204
model             744
condition       19665
cylinders       19791
fuel              206
odometer            0
title_status     1072
transmission      198
VIN             18652
drive           15622
size            36730
type            10634
paint_color     15613
image_url          29
description        30
state               0
lat               148
long              148
posting_date       29
dtype: int64

In [25]:
df["fuel"].value_counts()

fuel
gas         40920
other        4255
diesel       3511
hybrid        822
electric      286
Name: count, dtype: int64

In [26]:
# mode of fuel

df["fuel"].mode()

0    gas
Name: fuel, dtype: str

In [27]:
df["fuel"]=df["fuel"].fillna("unknown")

In [28]:
df["fuel"].isnull().sum()

np.int64(0)

In [29]:
# again check the missing values

df.isnull().sum()

id                  0
url                 0
region              0
region_url          0
price               0
year                0
manufacturer     2204
model             744
condition       19665
cylinders       19791
fuel                0
odometer            0
title_status     1072
transmission      198
VIN             18652
drive           15622
size            36730
type            10634
paint_color     15613
image_url          29
description        30
state               0
lat               148
long              148
posting_date       29
dtype: int64

In [30]:
# count ow many vehicles belong to each manufactuerer
df["manufacturer"].value_counts()

manufacturer
ford               7902
chevrolet          6500
toyota             4539
honda              2470
nissan             2459
ram                2050
jeep               1865
bmw                1797
mercedes-benz      1777
gmc                1771
dodge              1577
hyundai            1284
volkswagen         1262
kia                1189
lexus              1068
subaru              890
audi                797
cadillac            724
acura               719
mazda               615
chrysler            601
infiniti            537
buick               478
lincoln             408
volvo               396
mitsubishi          338
mini                338
rover               268
porsche             209
jaguar              206
pontiac             155
fiat                154
alfa-romeo          131
tesla               107
mercury              87
saturn               75
harley-davidson      21
ferrari              19
datsun               11
aston-martin          2
Name: count, dtype: int64

In [31]:
# filling missing manufacture data with unknown

df["manufacturer"]=df["manufacturer"].fillna("unknown")

In [32]:
# check if there are any other missing values in manufacture column
df["manufacturer"].isnull().sum()

np.int64(0)

In [33]:
df["model"].value_counts().head(20)

model
f-150             780
silverado 1500    634
altima            421
1500              381
2500              375
tacoma            363
camry             348
silverado         337
civic             332
accord            330
wrangler          294
mustang           275
corolla           272
fusion            234
prius             221
charger           220
jetta             218
malibu            217
tahoe             211
cr-v              208
Name: count, dtype: int64

In [34]:
# fill missing model with unknown

df["model"]=df["model"].fillna("unknown")

In [35]:
df.isnull().sum()

id                  0
url                 0
region              0
region_url          0
price               0
year                0
manufacturer        0
model               0
condition       19665
cylinders       19791
fuel                0
odometer            0
title_status     1072
transmission      198
VIN             18652
drive           15622
size            36730
type            10634
paint_color     15613
image_url          29
description        30
state               0
lat               148
long              148
posting_date       29
dtype: int64

In [36]:
df["condition"].value_counts()

condition
excellent    13478
good         12953
like new      2910
fair           782
new            115
salvage         97
Name: count, dtype: int64

In [37]:
df["condition"]=df["condition"].fillna("unknown")

In [38]:
df["condition"].isnull().sum()

np.int64(0)

In [39]:
df["condition"].value_counts()

condition
unknown      19665
excellent    13478
good         12953
like new      2910
fair           782
new            115
salvage         97
Name: count, dtype: int64

In [40]:
df.isnull().sum()

id                  0
url                 0
region              0
region_url          0
price               0
year                0
manufacturer        0
model               0
condition           0
cylinders       19791
fuel                0
odometer            0
title_status     1072
transmission      198
VIN             18652
drive           15622
size            36730
type            10634
paint_color     15613
image_url          29
description        30
state               0
lat               148
long              148
posting_date       29
dtype: int64

In [41]:
df["cylinders"].value_counts()

cylinders
6 cylinders     10769
4 cylinders     10070
8 cylinders      8590
other             307
5 cylinders       177
10 cylinders      156
3 cylinders       105
12 cylinders       35
Name: count, dtype: int64

In [42]:
df["cylinders"]=df["cylinders"].fillna("unknown")

In [43]:
df["cylinders"].isnull().sum()

np.int64(0)

In [44]:
df["title_status"].value_counts()

title_status
clean         47436
salvage         698
rebuilt         502
lien            157
missing         105
parts only       30
Name: count, dtype: int64

In [45]:
df["title_status"]=df["title_status"].fillna("unknown")

In [46]:
df.isnull().sum()

id                  0
url                 0
region              0
region_url          0
price               0
year                0
manufacturer        0
model               0
condition           0
cylinders           0
fuel                0
odometer            0
title_status        0
transmission      198
VIN             18652
drive           15622
size            36730
type            10634
paint_color     15613
image_url          29
description        30
state               0
lat               148
long              148
posting_date       29
dtype: int64

In [47]:
df["transmission"].value_counts()

transmission
automatic    39342
other         7244
manual        3216
Name: count, dtype: int64

In [48]:
df["transmission"]=df["transmission"].fillna("unknown")

In [49]:
df.isnull().sum()

id                  0
url                 0
region              0
region_url          0
price               0
year                0
manufacturer        0
model               0
condition           0
cylinders           0
fuel                0
odometer            0
title_status        0
transmission        0
VIN             18652
drive           15622
size            36730
type            10634
paint_color     15613
image_url          29
description        30
state               0
lat               148
long              148
posting_date       29
dtype: int64

In [50]:
df["VIN"].head(10)

0    NaN
1    NaN
2    NaN
3    NaN
4    NaN
5    NaN
6    NaN
7    NaN
8    NaN
9    NaN
Name: VIN, dtype: str

In [51]:
df.drive.value_counts()

drive
fwd    13242
4wd    12740
rwd     8396
Name: count, dtype: int64

In [52]:
df["drive"]=df["drive"].fillna("unknown")

In [53]:
df.isnull().sum()

id                  0
url                 0
region              0
region_url          0
price               0
year                0
manufacturer        0
model               0
condition           0
cylinders           0
fuel                0
odometer            0
title_status        0
transmission        0
VIN             18652
drive               0
size            36730
type            10634
paint_color     15613
image_url          29
description        30
state               0
lat               148
long              148
posting_date       29
dtype: int64

In [54]:
df["size"].value_counts()

size
full-size      7303
mid-size       3525
compact        2116
sub-compact     326
Name: count, dtype: int64

In [55]:
df["size"]=df["size"].fillna("unknown")

In [56]:
df.isnull().sum()

id                  0
url                 0
region              0
region_url          0
price               0
year                0
manufacturer        0
model               0
condition           0
cylinders           0
fuel                0
odometer            0
title_status        0
transmission        0
VIN             18652
drive               0
size                0
type            10634
paint_color     15613
image_url          29
description        30
state               0
lat               148
long              148
posting_date       29
dtype: int64

In [57]:
df["type"].value_counts()

type
sedan          10883
SUV             8249
pickup          5741
truck           3402
other           2843
coupe           2300
hatchback       2132
wagon           1145
convertible     1026
van              970
mini-van         469
offroad          149
bus               57
Name: count, dtype: int64

In [58]:
df["type"]=df["type"].fillna("unknown")

In [59]:
df.isnull().sum()

id                  0
url                 0
region              0
region_url          0
price               0
year                0
manufacturer        0
model               0
condition           0
cylinders           0
fuel                0
odometer            0
title_status        0
transmission        0
VIN             18652
drive               0
size                0
type                0
paint_color     15613
image_url          29
description        30
state               0
lat               148
long              148
posting_date       29
dtype: int64

In [60]:
df["paint_color"].value_counts()

paint_color
white     10838
black      6413
silver     5172
grey       3106
red        3104
blue       3039
custom      824
green       728
brown       691
yellow      217
orange      187
purple       68
Name: count, dtype: int64

In [61]:
df["paint_color"]=df["paint_color"].fillna("unknown")

In [62]:
df.isnull().sum()

id                  0
url                 0
region              0
region_url          0
price               0
year                0
manufacturer        0
model               0
condition           0
cylinders           0
fuel                0
odometer            0
title_status        0
transmission        0
VIN             18652
drive               0
size                0
type                0
paint_color         0
image_url          29
description        30
state               0
lat               148
long              148
posting_date       29
dtype: int64

In [63]:
df["image_url"].value_counts()

image_url
https://images.craigslist.org/00N0N_1xMPvfxRAIdz_0gw0co_600x450.jpg    703
https://images.craigslist.org/00R0R_lwWjXSEWNa7z_0x20oM_600x450.jpg    316
https://images.craigslist.org/00K0K_gsyasPjrBWuz_0CI0t2_600x450.jpg     39
https://images.craigslist.org/00l0l_2ibPc1hTVKTz_0jm0dl_600x450.jpg     37
https://images.craigslist.org/00z0z_cOLzInlBVQtz_04Y07g_600x450.jpg     35
                                                                      ...
https://images.craigslist.org/00v0v_5ublOx4t6Amz_0jm0ew_600x450.jpg      1
https://images.craigslist.org/00M0M_7mwuLXZeVaHz_0CI0hU_600x450.jpg      1
https://images.craigslist.org/00505_e5b1sfIeuiZz_0fe0bq_600x450.jpg      1
https://images.craigslist.org/00X0X_4Xe2JBmRvK7z_0ak07K_600x450.jpg      1
https://images.craigslist.org/00y0y_a4vhCOjMOuEz_0t20CI_600x450.jpg      1
Name: count, Length: 32857, dtype: int64

In [64]:
df["image_url"].isnull().sum()

np.int64(29)

In [65]:
df.isnull().sum()

id                  0
url                 0
region              0
region_url          0
price               0
year                0
manufacturer        0
model               0
condition           0
cylinders           0
fuel                0
odometer            0
title_status        0
transmission        0
VIN             18652
drive               0
size                0
type                0
paint_color         0
image_url          29
description        30
state               0
lat               148
long              148
posting_date       29
dtype: int64

In [66]:
df["description"].isnull().sum()

np.int64(30)

In [67]:
df["posting_date"].isnull().sum()

np.int64(29)

In [68]:
df[["lat", "long"]].isnull().sum()

lat     148
long    148
dtype: int64

In [69]:
df = df.dropna(subset=["lat", "long"])
df = df.reset_index(drop=True)

In [70]:
print(df.shape)
print(df[["lat", "long"]].isnull().sum())

(49852, 25)
lat     0
long    0
dtype: int64

In [71]:
df.isnull().sum()

id                  0
url                 0
region              0
region_url          0
price               0
year                0
manufacturer        0
model               0
condition           0
cylinders           0
fuel                0
odometer            0
title_status        0
transmission        0
VIN             18550
drive               0
size                0
type                0
paint_color         0
image_url           0
description         1
state               0
lat                 0
long                0
posting_date        0
dtype: int64

In [72]:
## 5. Duplicate Data
df.duplicated().sum()

np.int64(0)

In [73]:
df["id"].duplicated().sum()

np.int64(0)

In [74]:
# data types

df.dtypes

id                int64
url                 str
region              str
region_url          str
price             int64
year            float64
manufacturer        str
model               str
condition           str
cylinders           str
fuel                str
odometer        float64
title_status        str
transmission        str
VIN                 str
drive               str
size                str
type                str
paint_color         str
image_url           str
description         str
state               str
lat             float64
long            float64
posting_date        str
dtype: object

In [75]:
df["year"].describe()

count    49852.000000
mean      2011.189902
std         10.314196
min       1900.000000
25%       2008.000000
50%       2014.000000
75%       2017.000000
max       2022.000000
Name: year, dtype: float64

In [76]:
df["year"].head(10)

0    2014.0
1    2010.0
2    2020.0
3    2017.0
4    2013.0
5    2012.0
6    2016.0
7    2019.0
8    2016.0
9    2011.0
Name: year, dtype: float64

In [77]:
# check whether all years are whole numbers

(df["year"]%1==0).all()

np.True_

In [78]:
df["year"]=df["year"].astype(int)

In [79]:
df["year"].dtype

dtype('int64')

In [80]:
df["posting_date"].head()

0    2021-05-04T12:31:18-0500
1    2021-05-04T12:31:08-0500
2    2021-05-04T12:31:25-0500
3    2021-05-04T10:41:31-0500
4    2021-05-03T14:02:03-0500
Name: posting_date, dtype: str

In [81]:

df["posting_date"].dtype

In [82]:
df["posting_date"] = pd.to_datetime(
    df["posting_date"],
    errors="coerce",
    utc=True
)

In [83]:
df["posting_date"].dtype

datetime64[us, UTC]

In [84]:
df["posting_date"].isnull().sum()

np.int64(0)

In [85]:
df.isnull().sum()

id                  0
url                 0
region              0
region_url          0
price               0
year                0
manufacturer        0
model               0
condition           0
cylinders           0
fuel                0
odometer            0
title_status        0
transmission        0
VIN             18550
drive               0
size                0
type                0
paint_color         0
image_url           0
description         1
state               0
lat                 0
long                0
posting_date        0
dtype: int64

In [86]:
# text cleaning

text_columns = [
    "region",
    "manufacturer",
    "model",
    "condition",
    "cylinders",
    "fuel",
    "title_status",
    "transmission",
    "drive",
    "size",
    "type",
    "paint_color",
    "state"
]

for col in text_columns:
    df[col] = df[col].str.strip().str.lower()

In [87]:
df["manufacturer"].value_counts().head(10)

manufacturer
ford         7873
chevrolet    6486
toyota       4533
honda        2469
nissan       2458
unknown      2167
ram          2042
jeep         1864
bmw          1794
gmc          1768
Name: count, dtype: int64

In [88]:
df["fuel"].value_counts()

fuel
gas         40834
other        4252
diesel       3481
hybrid        822
electric      286
unknown       177
Name: count, dtype: int64

In [89]:
# Invalid Values

df["price"].describe()

count    4.985200e+04
mean     1.450245e+05
std      1.584194e+07
min      0.000000e+00
25%      6.100000e+03
50%      1.490000e+04
75%      2.699500e+04
max      3.009549e+09
Name: price, dtype: float64

In [90]:
df[df["price"] <= 0][
    ["price", "year", "manufacturer", "model"]
].head(20)

     price  year   manufacturer                   model
19       0  2011           jeep                 compass
99       0  2018      chevrolet       express cargo van
100      0  2019      chevrolet       express cargo van
101      0  2018      chevrolet       express cargo van
164      0  2015         nissan                  sentra
212      0  2019      chevrolet          silverado 1500
215      0  2014        unknown   freightliner cascadia
217      0  2017      chevrolet    silverado 2500hd 4x4
331      0  2017      chevrolet  silverado 2500 z71 4x4
332      0  2016            ram        3500 laramie 4x4
351      0  2018       infiniti                     q50
396      0  2020          dodge                 charger
399      0  2021         nissan                titan xd
403      0  2014        unknown   freightliner cascadia
449      0  2017            gmc             sierra 1500
456      0  2014          buick                 enclave
458      0  2018          honda                    cr v
504      0  2014        unknown   freightliner cascadia
506      0  2012      chevrolet        silverado 2500hd
513      0  2008  mercedes-benz                 e-class

In [91]:
(df["price"]<=0).sum()

np.int64(4747)

In [92]:
invalid_price_count=(df["price"]<=0).sum()
print("Invalid price records:", invalid_price_count)

Invalid price records: 4747

In [93]:
df=df[df["price"]>0].copy()

In [94]:
print("Rows remaining: ", df.shape[0])

print("Invalid prices remaining:", (df["price"]<=0).sum())

Rows remaining:  45105
Invalid prices remaining: 0

In [95]:
df.nlargest(20,"price")[
    ["price", "year", "manufacturer", "model", "odometer"]
]

            price  year   manufacturer                   model  odometer
37279  3009548743  2021      chevrolet                 unknown    1000.0
29261  1111111111  1999           ford  f350 super duty lariat  149000.0
37278  1111111111  2020           jeep                 unknown    1000.0
252     987654321  1960      chevrolet                 unknown  999999.0
1799     99999999  1993           ford                  ranger   99999.0
25957     1111111  2014      chevrolet                 unknown      11.0
45280      349999  2020        ferrari              f8 tributo    2800.0
44239      347999  2020        ferrari              f8 tributo    3000.0
43451      279888  2018        unknown        rolls royce dawn   14000.0
32900      255000  2018  mercedes-benz             g550 square    2000.0
28339      249999  2005        unknown  lamborghini murcielago    4478.0
14867      239995  2017        ferrari                 488 gtb    6450.0
16601      239995  2017        ferrari                 488 gtb    6012.0
8833       229500  2018        ferrari              488 spider    7910.0
9011       229500  2019        unknown        lamborghini urus   32922.0
8427       213000  1933           ford           2 dr victoria  999999.0
23196      179988  2021  mercedes-benz                 g-class   79015.0
36265      179988  2021  mercedes-benz                 g-class   79015.0
43482      179888  2018   aston-martin             martin db11    7800.0
45080      174700  2015        unknown      rolls-royce wraith   31973.0

In [96]:
(df["price"]> 1_000_000).sum()

np.int64(6)

In [97]:
df[df["price"] > 1_000_000][
    ["price", "year", "manufacturer", "model", "odometer", "condition"]
]

,price,year,manufacturer,model,odometer,condition
252,987654321,1960,chevrolet,unknown,999999.0,unknown
1799,99999999,1993,ford,ranger,99999.0,unknown
25957,1111111,2014,chevrolet,unknown,11.0,unknown
29261,1111111111,1999,ford,f350 super duty lariat,149000.0,good
37278,1111111111,2020,jeep,unknown,1000.0,unknown
37279,3009548743,2021,chevrolet,unknown,1000.0,unknown

In [98]:
df[df["price"]>1_000_000][
    ["price", "year", "manufacturer", "model", "odometer", "condition"]
]

,price,year,manufacturer,model,odometer,condition
252,987654321,1960,chevrolet,unknown,999999.0,unknown
1799,99999999,1993,ford,ranger,99999.0,unknown
25957,1111111,2014,chevrolet,unknown,11.0,unknown
29261,1111111111,1999,ford,f350 super duty lariat,149000.0,good
37278,1111111111,2020,jeep,unknown,1000.0,unknown
37279,3009548743,2021,chevrolet,unknown,1000.0,unknown

In [99]:
df = df[df["price"] <= 1_000_000].copy()

In [100]:
print("Rows remaining:", df.shape[0])
print("Prices above $1 million:", (df["price"] > 1_000_000).sum())
print("Maximum price:", df["price"].max())

Rows remaining: 45099
Prices above $1 million: 0
Maximum price: 349999

In [101]:
print("Minimum vehicle year:", df["year"].min())
print("Maximum vehicle year:", df["year"].max())

df.nlargest(10, "year")[
    ["year", "posting_date", "manufacturer", "model", "price"]
]

Minimum vehicle year: 1900
Maximum vehicle year: 2022

,year,posting_date,manufacturer,model,price
9666,2022,2021-04-07 22:56:59+00:00,unknown,suzuki vitara,6000
43039,2022,2021-04-29 02:16:46+00:00,toyota,4runner 4wd,11990
175,2021,2021-05-04 14:17:39+00:00,toyota,tacoma,32186
228,2021,2021-05-03 13:44:39+00:00,unknown,special finance program 2020,500
314,2021,2021-05-01 13:54:37+00:00,unknown,special finance program 2020,500
334,2021,2021-04-30 19:07:10+00:00,chevrolet,tahoe,72900
355,2021,2021-04-30 14:11:55+00:00,unknown,special finance program 2020,500
412,2021,2021-04-29 13:51:55+00:00,toyota,corolla,21334
416,2021,2021-04-29 13:47:14+00:00,unknown,special finance program 2020,500
429,2021,2021-04-28 21:12:26+00:00,chevrolet,corvette stingray spor,99950

In [102]:
df.nsmallest(15, "year")[
    ["year", "posting_date", "manufacturer", "model", "price", "odometer"]
]

,year,posting_date,manufacturer,model,price,odometer
29830,1900,2021-05-04 15:37:19+00:00,unknown,all,1,100000.0
32418,1900,2021-04-28 13:44:51+00:00,unknown,all,1,100000.0
42317,1900,2021-04-30 23:19:15+00:00,acura,rdx,38250,4500.0
44606,1900,2021-04-24 16:50:55+00:00,unknown,all,1,1000.0
10281,1901,2021-05-04 15:15:21+00:00,unknown,all,999,1.0
26593,1918,2021-04-27 18:45:25+00:00,ford,model t,16000,56000.0
9581,1922,2021-04-15 16:07:56+00:00,ford,t-bucket roadster,15000,80000.0
16325,1923,2021-04-23 16:30:35+00:00,buick,touring model,19500,58.0
21029,1923,2021-04-08 23:30:47+00:00,ford,t-bucket roadster,15000,1000.0
23250,1923,2021-04-08 20:19:20+00:00,unknown,1923 dort coupe,15000,22000.0
43673,1923,2021-04-27 15:25:07+00:00,unknown,paige,15500,300.0
12500,1924,2021-05-02 00:47:40+00:00,dodge,phaeton,22000,23480.0
35749,1924,2021-04-08 13:58:04+00:00,ford,unknown,8000,5000.0
3996,1926,2021-04-23 00:00:26+00:00,unknown,1926 nash,10995,20.0
43205,1926,2021-04-28 19:21:03+00:00,ford,t,7500,123456.0

In [103]:
(df["year"]<1910).sum()

np.int64(5)

In [104]:
df=df[df["year"]>1910].copy()

In [105]:

print("Rows remaining:", df.shape[0])
print("Minimum vehicle year:", df["year"].min())
print("Years before 1910:", (df["year"] < 1910).sum())

Rows remaining: 45094
Minimum vehicle year: 1918
Years before 1910: 0

In [106]:
listing_year=df["posting_date"].dt.year
(df["year"]>listing_year).sum()

np.int64(2)

In [107]:
listing_year = df["posting_date"].dt.year

df.loc[
    df["year"] > listing_year,
    ["year", "posting_date", "manufacturer", "model", "price"]
]

       year              posting_date manufacturer          model  price
9666   2022 2021-04-07 22:56:59+00:00      unknown  suzuki vitara   6000
43039  2022 2021-04-29 02:16:46+00:00       toyota    4runner 4wd  11990

In [108]:
df.loc[
    df["odometer"] < 0,
    ["odometer", "year", "manufacturer", "model", "price"]
]

Empty DataFrame
Columns: [odometer, year, manufacturer, model, price]
Index: []

In [109]:
df["odometer"].describe()

count    4.509400e+04
mean     9.425914e+04
std      2.086166e+05
min      0.000000e+00
25%      3.508050e+04
50%      7.939000e+04
75%      1.272610e+05
max      1.000000e+07
Name: odometer, dtype: float64

In [110]:
df.nlargest(10, "odometer")[
    ["odometer", "year", "manufacturer", "model", "price"]
]

         odometer  year manufacturer      model  price
9149   10000000.0  1975         ford       f250   4000
22983  10000000.0  1957    chevrolet      nomad  15000
28618  10000000.0  1951    chevrolet        coe  20000
34589  10000000.0  1962    chevrolet     impala     13
44132  10000000.0  1975      porsche        914  16000
423     9999999.0  1929         ford    unknown  22500
12848   9999999.0  1975   volkswagen     beetle   2500
24970   9999999.0  1949        dodge  swb panel    150
26852   9999999.0  1996         ford   explorer   1499
27081   9999999.0  1989        buick    lesabre   1500

In [111]:
((df["odometer"] == 9_999_999) |
 (df["odometer"] == 10_000_000)).sum()

np.int64(14)

In [112]:
import numpy as np

df.loc[
    df["odometer"].isin([9_999_999, 10_000_000]),
    "odometer"
] = np.nan

In [113]:
print("Missing odometer values:", df["odometer"].isna().sum())
print("Maximum odometer:", df["odometer"].max())

Missing odometer values: 14
Maximum odometer: 9750924.0

In [114]:
print("Invalid latitudes:", 
      ((df["lat"] < -90) | (df["lat"] > 90)).sum())

print("Invalid longitudes:", 
      ((df["long"] < -180) | (df["long"] > 180)).sum())

Invalid latitudes: 0
Invalid longitudes: 0

In [115]:
print("Fuel values:")
print(df["fuel"].value_counts())

print("\nTransmission values:")
print(df["transmission"].value_counts())

print("\nCondition values:")
print(df["condition"].value_counts())

print("\nTitle status values:")
print(df["title_status"].value_counts())

Fuel values:
fuel
gas         37245
other        3550
diesel       3080
hybrid        772
electric      273
unknown       174
Name: count, dtype: int64

Transmission values:
transmission
automatic    34853
other         7037
manual        3102
unknown        102
Name: count, dtype: int64

Condition values:
condition
unknown      16408
excellent    12629
good         12605
like new      2472
fair           777
new            106
salvage         97
Name: count, dtype: int64

Title status values:
title_status
clean         42694
unknown         917
salvage         694
rebuilt         501
lien            157
missing         102
parts only       29
Name: count, dtype: int64

In [116]:
df.isnull().sum()

id                  0
url                 0
region              0
region_url          0
price               0
year                0
manufacturer        0
model               0
condition           0
cylinders           0
fuel                0
odometer           14
title_status        0
transmission        0
VIN             17312
drive               0
size                0
type                0
paint_color         0
image_url           0
description         1
state               0
lat                 0
long                0
posting_date        0
dtype: int64

In [117]:
# Outliers

Q1=df["price"].quantile(0.25)
Q3=df["price"].quantile(0.75)

IQR=Q3-Q1

lower_bound=Q1-1.5*IQR
upper_bound=Q3+1.5*IQR

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower bound:", lower_bound)
print("Upper bound:", upper_bound)

Q1: 8499.0
Q3: 28590.0
IQR: 20091.0
Lower bound: -21637.5
Upper bound: 58726.5

In [118]:
price_outliers=df[df["price"]>upper_bound]

print("Potential high-price outliers:", len(price_outliers))

Potential high-price outliers: 1214

In [119]:
price_outliers.nlargest(15,"price")[
    ["price", "year", "manufacturer", "model", "odometer", "condition"] 
]

,price,year,manufacturer,model,odometer,condition
45280,349999,2020,ferrari,f8 tributo,2800.0,excellent
44239,347999,2020,ferrari,f8 tributo,3000.0,excellent
43451,279888,2018,unknown,rolls royce dawn,14000.0,excellent
32900,255000,2018,mercedes-benz,g550 square,2000.0,unknown
28339,249999,2005,unknown,lamborghini murcielago,4478.0,like new
14867,239995,2017,ferrari,488 gtb,6450.0,unknown
16601,239995,2017,ferrari,488 gtb,6012.0,unknown
8833,229500,2018,ferrari,488 spider,7910.0,unknown
9011,229500,2019,unknown,lamborghini urus,32922.0,unknown
8427,213000,1933,ford,2 dr victoria,999999.0,unknown
23196,179988,2021,mercedes-benz,g-class,79015.0,excellent
36265,179988,2021,mercedes-benz,g-class,79015.0,excellent
43482,179888,2018,aston-martin,martin db11,7800.0,like new
45080,174700,2015,unknown,rolls-royce wraith,31973.0,excellent
43086,169888,2020,mercedes-benz,amg gt s,2100.0,like new

In [120]:

odo_q1=df["odometer"].quantile(0.25)
odo_q3=df["odometer"].quantile(0.75)

odo_iqr = odo_q3 - odo_q1

odo_upper_bound=odo_q3 + 1.5*odo_iqr

print("Odometer Q1:", odo_q1)
print("Odometer Q3:", odo_q3)
print("Odometer IQR:", odo_iqr)
print("Upper bound:", odo_upper_bound)

Odometer Q1: 35068.75
Odometer Q3: 127156.25
Odometer IQR: 92087.5
Upper bound: 265287.5

In [121]:
odometer_outliers=df[df["odometer"]> odo_upper_bound]

print("Potential high-mileage outliers:", len(odometer_outliers))

Potential high-mileage outliers: 617

In [122]:
odometer_outliers.nlargest(15,"odometer")[
    ["year", "manufacturer", "model", "odometer", "price", "condition"]

    
]

       year   manufacturer                 model   odometer  price  condition
23449  1998            gmc                 yukon  9750924.0   2800       fair
32858  1965      chevrolet                impala  8393929.0  13000    unknown
13439  1991           ford      f-150 xlt lariet  8000000.0   1750       good
13436  1988      chevrolet           express van  7654321.0   1550       good
33314  1940       cadillac               unknown  4000000.0   3500    unknown
34876  1997        unknown         peterbilt 379  2308454.0  32000    unknown
530    2014            ram              2500 4x4  2222222.0  27990   like new
13962  1998      chevrolet               ck 2500  2076920.0   3500       fair
32764  2005           ford            mustang gt  2006000.0   4200  excellent
26838  1997          rover               unknown  2000000.0   1999    unknown
26841  2002        unknown         mercades benz  2000000.0   1999    unknown
36682  2011      chevrolet               unknown  1870000.0  16500  excellent
18339  2010         subaru              forester  1753761.0    800  excellent
33323  2006  mercedes-benz             benz e350  1500005.0   4999  excellent
33289  2008         nissan  altima 2.5 4dr sedan  1252993.0   3250  excellent

In [123]:
suspicious_odometer=df[df["odometer"]> 1_000_000]

print("Readings above 1,000,000 miles:", len(suspicious_odometer))

Readings above 1,000,000 miles: 31

In [124]:
display(

    suspicious_odometer[
        ["year", "manufacturer", "model", "odometer", "price", "condition"]]

    .sort_values("odometer", ascending=False)

        
    
)

,year,manufacturer,model,odometer,price,condition
23449,1998,gmc,yukon,9750924.0,2800,fair
32858,1965,chevrolet,impala,8393929.0,13000,unknown
13439,1991,ford,f-150 xlt lariet,8000000.0,1750,good
13436,1988,chevrolet,express van,7654321.0,1550,good
33314,1940,cadillac,unknown,4000000.0,3500,unknown
34876,1997,unknown,peterbilt 379,2308454.0,32000,unknown
530,2014,ram,2500 4x4,2222222.0,27990,like new
13962,1998,chevrolet,ck 2500,2076920.0,3500,fair
32764,2005,ford,mustang gt,2006000.0,4200,excellent
26838,1997,rover,unknown,2000000.0,1999,unknown
26841,2002,unknown,mercades benz,2000000.0,1999,unknown
36682,2011,chevrolet,unknown,1870000.0,16500,excellent
18339,2010,subaru,forester,1753761.0,800,excellent
33323,2006,mercedes-benz,benz e350,1500005.0,4999,excellent
33289,2008,nissan,altima 2.5 4dr sedan,1252993.0,3250,excellent
33423,2014,volkswagen,passat tsi se,1250003.0,8500,good
16843,1936,chrysler,unknown,1239494.0,12345,unknown
13437,1960,unknown,rambler american,1234689.0,1400,good
7589,1977,ford,unknown,1234567.0,1900,unknown
4548,2021,unknown,other,1234567.0,200,unknown
35502,1948,chevrolet,fleetline,1222334.0,6300,good
24341,1976,unknown,1976 cougar,1222222.0,2500,salvage
25017,1976,unknown,1976 cougar,1222222.0,2500,salvage
33277,1965,chevrolet,c10,1111111.0,15,unknown
23663,1952,unknown,hudson commodore,1111111.0,1500,fair
583,2018,ford,edge sel,1111111.0,17990,like new
9806,2008,lincoln,mkz,1111111.0,2500,good
36050,1989,unknown,suzuki sidekick sport,1111111.0,2500,excellent
24961,1952,unknown,hudson commodore,1111111.0,1500,fair
24662,2008,unknown,freightliner columbia 70' raised,1075000.0,10000,good
33761,2009,volvo,unknown,1017923.0,22500,fair

In [125]:
df.loc[df["odometer"]>1_000_000,"odometer"]=np.nan

print("Reading above 1,000,000 miles:", (df["odometer"]>1_000_000).sum())

Reading above 1,000,000 miles: 0

In [126]:
df.isnull().sum()

id                  0
url                 0
region              0
region_url          0
price               0
year                0
manufacturer        0
model               0
condition           0
cylinders           0
fuel                0
odometer           45
title_status        0
transmission        0
VIN             17312
drive               0
size                0
type                0
paint_color         0
image_url           0
description         1
state               0
lat                 0
long                0
posting_date        0
dtype: int64

In [127]:
print(
    "Remaining high-mileage outliers:",
    (df["odometer"] > odo_upper_bound).sum()
)

Remaining high-mileage outliers: 586

In [128]:
# feature creation( vehicle age)

df["listing_year"]=df["posting_date"].dt.year

df["vehicle_age"]=df["listing_year"]-df["year"]

df[["year", "posting_date", "listing_year", "vehicle_age"]].head()

   year              posting_date  listing_year  vehicle_age
0  2014 2021-05-04 17:31:18+00:00          2021            7
1  2010 2021-05-04 17:31:08+00:00          2021           11
2  2020 2021-05-04 17:31:25+00:00          2021            1
3  2017 2021-05-04 15:41:31+00:00          2021            4
4  2013 2021-05-03 19:02:03+00:00          2021            8

In [129]:
print("Negative vehicle ages:", (df["vehicle_age"]<0).sum())

print("Minimum vehicle age:", df["vehicle_age"].min())

print("Maximum vehicle age:", df["vehicle_age"].max())

print("Missing vehicles ages:", df["vehicle_age"].isna().sum())

Negative vehicle ages: 2
Minimum vehicle age: -1
Maximum vehicle age: 103
Missing vehicles ages: 0

In [130]:
df.loc[

    df["vehicle_age"]<0,

    ["year", "posting_date", "listing_year", "vehicle_age",
     "manufacturer", "model", "price"] 
]

,year,posting_date,listing_year,vehicle_age,manufacturer,model,price
9666,2022,2021-04-07 22:56:59+00:00,2021,-1,unknown,suzuki vitara,6000
43039,2022,2021-04-29 02:16:46+00:00,2021,-1,toyota,4runner 4wd,11990

In [131]:
df.loc[df["vehicle_age"]<0,"vehicle_age"]=np.nan
print("Negative vehicle ages:", (df["vehicle_age"] < 0).sum())
print("Missing vehicle ages:", df["vehicle_age"].isna().sum())

Negative vehicle ages: 0
Missing vehicle ages: 2

In [132]:
df["mileage_category"]=pd.cut(

    df["odometer"],
    bins=[-1,30_000,60_000,100_000,200_000, float("inf")],
    labels=[

        "Very Low",
        "Low",
        "Medium",
        "High",
        "Very High"

    ]
)
df[["odometer", "mileage_category"]].head(10)

   odometer mileage_category
0   57923.0              Low
1   71229.0           Medium
2   19160.0         Very Low
3   41124.0              Low
4  128000.0             High
5   68696.0           Medium
6   29499.0         Very Low
7   43000.0              Low
8   17302.0         Very Low
9   30237.0              Low

In [133]:
print(df["mileage_category"].value_counts())

print("\n Missing mileage categories:", df["mileage_category"].isna().sum())

mileage_category
High         14787
Medium       10654
Very Low      9587
Low           7632
Very High     2389
Name: count, dtype: int64

 Missing mileage categories: 45

In [134]:
df["price_category"]=pd.cut(
    df["price"],
    bins=[0,10_000,25_000,50_000,float("inf")],

    labels=[
        "Budget",
        "Mid-Range",
        "Expensive",
        "Luxury"
    ]
    
)
df[["price","price_category"]].head(10)

   price price_category
0  33590      Expensive
1  22590      Mid-Range
2  39590      Expensive
3  30990      Expensive
4  15000      Mid-Range
5  27990      Expensive
6  34590      Expensive
7  35000      Expensive
8  29990      Expensive
9  38590      Expensive

In [135]:
print(df["price_category"].value_counts())

print("\nMissing price categories:",
      df["price_category"].isna().sum())

price_category
Mid-Range    16618
Budget       14525
Expensive    11982
Luxury        1969
Name: count, dtype: int64

Missing price categories: 0

In [136]:
print("Final dataset shape:", df.shape)
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

Final dataset shape: (45094, 29)
Number of rows: 45094
Number of columns: 29

In [137]:
missing_values = df.isna().sum()

print(missing_values[missing_values > 0].sort_values(ascending=False))

VIN                 17312
odometer               45
mileage_category       45
vehicle_age             2
description             1
dtype: int64

In [138]:
print("Duplicated rows:", df.duplicated().sum())
print("Duplicated vehicle Ids:", df["id"].duplicated().sum())
print("Are all vehicles IDs unique?", df["id"].is_unique)

Duplicated rows: 0
Duplicated vehicle Ids: 0
Are all vehicles IDs unique? True

In [139]:
print("Prices <= 0:", (df["price"] <= 0).sum())

print("Years before 1910:", (df["year"] < 1910).sum())

print("Negative odometer readings:", (df["odometer"] < 0).sum())

print("Odometer readings above 1 million:",
      (df["odometer"] > 1_000_000).sum())

print("Invalid latitude:",
      ((df["lat"] < -90) | (df["lat"] > 90)).sum())

print("Invalid longitude:",
      ((df["long"] < -180) | (df["long"] > 180)).sum())

print("Negative vehicle ages:",
      (df["vehicle_age"] < 0).sum())

Prices <= 0: 0
Years before 1910: 0
Negative odometer readings: 0
Odometer readings above 1 million: 0
Invalid latitude: 0
Invalid longitude: 0
Negative vehicle ages: 0

In [140]:
df.dtypes

id                                int64
url                                 str
region                              str
region_url                          str
price                             int64
year                              int64
manufacturer                        str
model                               str
condition                           str
cylinders                           str
fuel                                str
odometer                        float64
title_status                        str
transmission                        str
VIN                                 str
drive                               str
size                                str
type                                str
paint_color                         str
image_url                           str
description                         str
state                               str
lat                             float64
long                            float64
posting_date        datetime64[us, UTC]
listing_year                      int32
vehicle_age                     float64
mileage_category               category
price_category                 category
dtype: object

In [141]:
df.to_csv("../data/vehicles_cleaned.csv", index=False)