In [1]:
import pandas as pd
import numpy as np

df= pd.read_csv("../data/vehicles_cleaned.csv")

print("Dataset loaded successfully!")
print("Dataset shape:", df.shape)

Dataset loaded successfully!
Dataset shape: (45094, 29)

In [2]:
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])
print("Total number of cells:", df.size)

Number of rows: 45094
Number of columns: 29
Total number of cells: 1307726

In [3]:
# identifying data types
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 45094 entries, 0 to 45093
Data columns (total 29 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                45094 non-null  int64
 1   url               45094 non-null  str
 2   region            45094 non-null  str
 3   region_url        45094 non-null  str
 4   price             45094 non-null  int64
 5   year              45094 non-null  int64
 6   manufacturer      45094 non-null  str
 7   model             45094 non-null  str
 8   condition         45094 non-null  str
 9   cylinders         45094 non-null  str
 10  fuel              45094 non-null  str
 11  odometer          45049 non-null  float64
 12  title_status      45094 non-null  str
 13  transmission      45094 non-null  str
 14  VIN               27782 non-null  str
 15  drive             45094 non-null  str
 16  size              45094 non-null  str
 17  type              45094 non-null  str
 18  paint_color       45094 non-null  str
 19  image_url         45094 non-null  str
 20  description       45093 non-null  str
 21  state             45094 non-null  str
 22  lat               45094 non-null  float64
 23  long              45094 non-null  float64
 24  posting_date      45094 non-null  str
 25  listing_year      45094 non-null  int64
 26  vehicle_age       45092 non-null  float64
 27  mileage_category  45049 non-null  str
 28  price_category    45094 non-null  str
dtypes: float64(4), int64(4), str(21)
memory usage: 10.0 MB

In [4]:
# categorizing columns

numerical_columns=df.select_dtypes(

    include=["int64","float64"]
    
).columns.tolist()


text_columns=df.select_dtypes(

    include=["str","object"]
    
).columns.tolist()

print("Numerical columns:")
print(numerical_columns)

print("\nText columns:")
print(text_columns)

Numerical columns:
['id', 'price', 'year', 'odometer', 'lat', 'long', 'listing_year', 'vehicle_age']

Text columns:
['url', 'region', 'region_url', 'manufacturer', 'model', 'condition', 'cylinders', 'fuel', 'title_status', 'transmission', 'VIN', 'drive', 'size', 'type', 'paint_color', 'image_url', 'description', 'state', 'posting_date', 'mileage_category', 'price_category']

In [5]:
# Identified the columns and their analytical purposes

for number, column in enumerate(df.columns, start=1):
    print(f"{number}. {column}")

1. id
2. url
3. region
4. region_url
5. price
6. year
7. manufacturer
8. model
9. condition
10. cylinders
11. fuel
12. odometer
13. title_status
14. transmission
15. VIN
16. drive
17. size
18. type
19. paint_color
20. image_url
21. description
22. state
23. lat
24. long
25. posting_date
26. listing_year
27. vehicle_age
28. mileage_category
29. price_category

In [6]:
#EDA Step 2 — Vehicle Price Analysis

# Average, median, minimum and maximum price


print("Mean price:", df["price"].mean())
print("Median price:", df["price"].median())
print("Minimum price:", df["price"].min())
print("Maximum price:", df["price"].max())

Mean price: 20162.0606954362
Median price: 16590.0
Minimum price: 1
Maximum price: 349999

In [7]:
df.nsmallest(10,"price")[
    ["price","year","manufacturer","model","condition","odometer"]
    
    ].to_string(index=False)

' price  year manufacturer            model condition  odometer\n     1  2012         ford  f250 super duty   unknown  150000.0\n     1  2002       nissan           maxima   unknown  196000.0\n     1  2003     cadillac     escalade esv   unknown  315836.0\n     1  1999      unknown 1999 ply,prowler      good    1000.0\n     1  2005          gmc            envoy excellent  181000.0\n     1  2012      unknown              all      good  100000.0\n     1  2006        acura              tsx   unknown  192000.0\n     1  2012    chevrolet           malibu   unknown  268000.0\n     1  2001        honda           accord   unknown  210000.0\n     1  2006        honda           accord   unknown  166000.0'

In [8]:
# How many vehicles are listed for $1?

one_dollar_count=(df["price"]==1).sum()

print("Vehicles listed of $1:",one_dollar_count)

print("Percentage of dataset:", round(one_dollar_count/len(df)*100,2), "%")

Vehicles listed of $1: 123
Percentage of dataset: 0.27 %

In [9]:
# Price distribution

df["price"].describe()

count     45094.000000
mean      20162.060695
std       16195.275324
min           1.000000
25%        8499.000000
50%       16590.000000
75%       28590.000000
max      349999.000000
Name: price, dtype: float64

In [10]:
q1=df["price"].quantile(0.25)
q3=df["price"].quantile(0.75)

iqr=q3-q1

print("First quartile (Q1):", q1)
print("Third quartile (Q3):", q3)
print("Interquartile range (IQR):", iqr)

First quartile (Q1): 8499.0
Third quartile (Q3): 28590.0
Interquartile range (IQR): 20091.0

In [11]:
#  outlier boundries
lower_bound=q1-1.5*iqr
upper_bound=q3+1.5*iqr
print("Lower boundary:", lower_bound)
print("Upper boundary:", upper_bound)

Lower boundary: -21637.5
Upper boundary: 58726.5

In [12]:
high_price_outliers = df[df["price"] > upper_bound]

print("Number of potential high-price outliers:", len(high_price_outliers))

print(
    "Percentage of dataset:",
    round(len(high_price_outliers) / len(df) * 100, 2),
    "%"
)

Number of potential high-price outliers: 1214
Percentage of dataset: 2.69 %

In [13]:
# Inspect the 10 most expensive vehicles
df.nlargest(10,"price")[
  ["price", "year", "manufacturer", "model", "condition", "odometer"]
    
]

,price,year,manufacturer,model,condition,odometer
40871,349999,2020,ferrari,f8 tributo,excellent,2800.0
39921,347999,2020,ferrari,f8 tributo,excellent,3000.0
39192,279888,2018,unknown,rolls royce dawn,excellent,14000.0
29446,255000,2018,mercedes-benz,g550 square,unknown,2000.0
25873,249999,2005,unknown,lamborghini murcielago,like new,4478.0
14289,239995,2017,ferrari,488 gtb,unknown,6450.0
15912,239995,2017,ferrari,488 gtb,unknown,6012.0
8578,229500,2018,ferrari,488 spider,unknown,7910.0
8756,229500,2019,unknown,lamborghini urus,unknown,32922.0
8174,213000,1933,ford,2 dr victoria,unknown,999999.0

In [14]:
# Analyze price categories

# Which price category contains the most vehicle listings?

df["price_category"].value_counts()

price_category
Mid-Range    16618
Budget       14525
Expensive    11982
Luxury        1969
Name: count, dtype: int64

In [15]:
price_counts=df["price_category"].value_counts()

price_percentage=(
    df["price_category"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)

    
)
print("Price category counts:")
print(price_counts)

print("\nPrice category percentages:")
print(price_percentage)

Price category counts:
price_category
Mid-Range    16618
Budget       14525
Expensive    11982
Luxury        1969
Name: count, dtype: int64

Price category percentages:
price_category
Mid-Range    36.85
Budget       32.21
Expensive    26.57
Luxury        4.37
Name: proportion, dtype: float64

In [16]:
# Manufacturer popularity
# Which are the top 10 most common vehicle manufacturers in the dataset?

df["manufacturer"].value_counts().head()

manufacturer
ford         7020
chevrolet    5800
toyota       4093
honda        2221
nissan       2194
Name: count, dtype: int64

In [17]:
#How many different manufacturers are in the dataset?

df["manufacturer"].nunique()

41

In [18]:

# How many listings have the manufacturer recorded as unknown?
unknown_count=(df["manufacturer"]=="unknown").sum()

print("Listing with unknown manufacturer:", unknown_count)

print("Percentage:", round(unknown_count/len(df)*100,2), "%")

Listing with unknown manufacturer: 1979
Percentage: 4.39 %

In [19]:
# Are there any missing manufacturer values?
missing_count=df["manufacturer"].isna().sum()

print("Missing manufacturer values:", missing_count)

print(
    "Percentage:",
    round(missing_count/len(df)*100,2),
    "%"
)

Missing manufacturer values: 0
Percentage: 0.0 %

In [20]:
# What percentage of listings belongs to each of the top 10 manufacturers

top_10=df["manufacturer"].value_counts().head(10)

top_10_percentages=(

    (top_10/len(df))*100
    
).round(2)

manufacturer_summary=pd.DataFrame({
    "Listings": top_10,
    "Percentage": top_10_percentages

    
})

manufacturer_summary

               Listings  Percentage
manufacturer
ford               7020       15.57
chevrolet          5800       12.86
toyota             4093        9.08
honda              2221        4.93
nissan             2194        4.87
unknown            1979        4.39
ram                1836        4.07
bmw                1685        3.74
jeep               1651        3.66
mercedes-benz      1611        3.57

In [21]:
# Which manufacturer has the highest average vehicle price?

average_price=(

    df.groupby("manufacturer")["price"].mean().sort_values(ascending=False))


average_price.head(10).round(2)

manufacturer
ferrari         159773.76
aston-martin    109944.00
porsche          35447.49
tesla            34943.47
ram              31479.62
alfa-romeo       30238.03
rover            28989.33
jaguar           27255.21
gmc              25911.77
audi             24966.30
Name: price, dtype: float64

In [22]:
# Which manufacturers have the highest median vehicle prices

median_price=(
    df.groupby("manufacturer")["price"]
    .median()
    .sort_values(ascending=False)
)

median_price.head(10).round(2)

manufacturer
aston-martin    109944.0
ferrari         105000.0
tesla            37290.0
jaguar           30290.0
alfa-romeo       29990.0
ram              29990.0
porsche          29497.5
rover            27590.0
gmc              25525.0
audi             24748.5
Name: price, dtype: float64

In [23]:
top_manufacturers=df["manufacturer"].value_counts().head(10)

top_manufacturers

manufacturer
ford             7020
chevrolet        5800
toyota           4093
honda            2221
nissan           2194
unknown          1979
ram              1836
bmw              1685
jeep             1651
mercedes-benz    1611
Name: count, dtype: int64

In [24]:
manufacturer_comparison = df.groupby("manufacturer").agg(
    listing_count=("price", "count"),
    average_price=("price", "mean")
)

manufacturer_comparison = manufacturer_comparison.sort_values(
    by="listing_count",
    ascending=False
)

manufacturer_comparison.head(10).round(2)

               listing_count  average_price
manufacturer
ford                    7020       22421.89
chevrolet               5800       22410.91
toyota                  4093       17204.35
honda                   2221       12911.10
nissan                  2194       12907.95
unknown                 1979       21987.93
ram                     1836       31479.62
bmw                     1685       19999.04
jeep                    1651       22559.83
mercedes-benz           1611       24570.41

In [25]:
#How many vehicles have an odometer reading below 50,000?

low_mileage_count=(df["odometer"]<50000).sum()

print("Vehicles with odometer below 50,000:",
      low_mileage_count)

Vehicles with odometer below 50,000: 15015

In [26]:
# 4B  What is the average vehicle age?

print("Average vehicle age:", df["vehicle_age"].mean(), "years")

Average vehicle age: 10.152754368845915 years

In [27]:
print("Median Price age:", df["vehicle_age"].median(), "years")

Median Price age: 7.0 years

In [28]:
# What is the youngest vehicle in the dataset?

print("Youngest vehicle age:", df["vehicle_age"].min(), "years")

Youngest vehicle age: 0.0 years

In [29]:
# oldest vehicle
print("Oldest Vehicle:", df["vehicle_age"].max(), "years")

Oldest Vehicle: 103.0 years

In [30]:
# How many vehicles are less than 5 years old?

under_5_years=(df["vehicle_age"]<5).sum()

print("Vehicle less than  years old:", under_5_years)

Vehicle less than  years old: 13240

In [31]:
#How many vehicles are between 5 and 10 years old?

between_5_and_10=(
    (df["vehicle_age"]>=5) &
    (df["vehicle_age"]<=10)
).sum()

print("Vehicles between 5 and 10 years old:", between_5_and_10)

Vehicles between 5 and 10 years old: 17324

In [32]:
#How many vehicles are more than 10 years old?
old_10=(
    (df["vehicle_age"]>10).sum()
)

print("vehicles older that 10 years:", old_10)

vehicles older that 10 years: 14528

In [33]:
average_age_by_manufacturer=(

    df.groupby("manufacturer")["vehicle_age"]
    .mean()
    .sort_values(ascending=True)
    
)
average_age_by_manufacturer.round(2)

manufacturer
alfa-romeo          3.66
tesla               4.71
kia                 5.63
audi                6.63
mitsubishi          6.83
hyundai             6.87
fiat                6.91
acura               6.99
infiniti            7.39
ram                 7.62
nissan              7.66
mini                7.73
subaru              8.15
volvo               8.32
mazda               8.37
jaguar              8.38
bmw                 8.51
rover               8.96
lincoln             9.07
jeep                9.20
cadillac            9.40
aston-martin        9.50
dodge               9.53
honda               9.59
volkswagen          9.69
lexus               9.94
gmc                10.01
chrysler           10.17
toyota             10.33
mercedes-benz      10.44
buick              11.02
ford               11.61
chevrolet          11.99
ferrari            13.35
porsche            13.47
saturn             15.88
harley-davidson    16.33
unknown            16.55
pontiac            26.11
mercury            27.52
datsun             48.00
Name: vehicle_age, dtype: float64

In [34]:
vehicle_count_by_age=(
    df.groupby("vehicle_age")
    .size()
    .sort_index()
)

vehicle_count_by_age

vehicle_age
0.0       445
1.0      2151
2.0      2891
3.0      3860
4.0      3893
         ...
95.0        2
97.0        2
98.0        4
99.0        1
103.0       1
Length: 97, dtype: int64

In [35]:
# 4C — Mileage Category Analysis
#How many vehicles belong to each mileage category?

mileage_counts=df["mileage_category"].value_counts()

print(mileage_counts)

mileage_category
High         14787
Medium       10654
Very Low      9587
Low           7632
Very High     2389
Name: count, dtype: int64

In [36]:
# percentage of mileage category
mileage_percentages = (
    df["mileage_category"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

print(mileage_percentages)

mileage_category
High         32.82
Medium       23.65
Very Low     21.28
Low          16.94
Very High     5.30
Name: proportion, dtype: float64

In [37]:
#Which mileage category contains the most vehicles?

print(df["mileage_category"].value_counts().idxmax())

High

In [38]:
#Which mileage category contains the fewest vehicles?

df["mileage_category"].value_counts().idxmin()

'Very High'

In [39]:
#  Vehicle Age and Mileage Relationships
#  We'll use the correlation between vehicle_age and odometer.

df["vehicle_age"].corr(df["odometer"])

np.float64(0.30030990696413645)

In [40]:
# Question 21 — What is the average odometer reading for each vehicle age group?

df.groupby("vehicle_age")["odometer"].mean().round(2)

vehicle_age
0.0       3047.07
1.0      13955.20
2.0      23987.47
3.0      38080.23
4.0      52192.26
           ...
95.0     61738.00
97.0     14240.00
98.0      5839.50
99.0     80000.00
103.0    56000.00
Name: odometer, Length: 97, dtype: float64

In [41]:


Q1=df["odometer"].quantile(0.25)

Q3=df["odometer"].quantile(0.75)

IQR=Q3-Q1

upper_limit=Q3+1.5*IQR

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Upper outlier limit:", upper_limit)

Q1: 35036.0
Q3: 127036.0
IQR: 92000.0
Upper outlier limit: 265036.0

In [42]:
high_mileage_outliers=(df["odometer"]>upper_limit).sum()

print("Number of high-mileage outliers", high_mileage_outliers)

Number of high-mileage outliers 586

In [43]:
outlier_percentage = (high_mileage_outliers / df["odometer"].count()) * 100

print("Percentage of high-mileage outliers:", round(outlier_percentage, 2), "%")

Percentage of high-mileage outliers: 1.3 %

In [44]:
# Section 5A  Correlation between price and mileage


df["price"].corr(df["odometer"])

np.float64(-0.40326802650899485)

In [45]:
#Compare average prices across mileage categories

df.groupby("mileage_category")["price"].mean().round(2)

mileage_category
High         12030.33
Low          26772.31
Medium       19583.81
Very High     9254.40
Very Low     30865.59
Name: price, dtype: float64

In [46]:
# Which mileage category has the highest average price?

print(df.groupby("mileage_category")["price"].mean().idxmax())

Very Low

In [48]:
#Section 5B — Price and Vehicle Age


df["vehicle_age"].corr(df["price"])

#**Finding:** Vehicle age and listing price have a weak negative correlation (r ≈ −0.28). This suggests that older vehicles generally tend to have lower listing prices, although vehicle age alone does not fully explain price differences.

np.float64(-0.28431574454143793)

In [49]:
#What is the average price for each vehicle age?

df.groupby("vehicle_age")["price"].mean().round(2)

# **Finding:** Average listing prices vary across vehicle-age groups. In the younger age groups, the average price decreases from $37,224.42 for 1-year-old vehicles to $27,656.92 for 4-year-old vehicles. This suggests that vehicle age may be associated with listing price, although the trend should be assessed across all age groups.

vehicle_age
0.0      23236.06
1.0      37224.42
2.0      34385.92
3.0      30036.50
4.0      27656.92
           ...
95.0      9247.50
97.0     15000.00
98.0     16250.00
99.0     15000.00
103.0    16000.00
Name: price, Length: 97, dtype: float64

In [50]:
# Which vehicle age has the highest average price?

df.groupby("vehicle_age")["price"].mean().idxmax()

np.float64(88.0)

In [51]:
df[df["vehicle_age"] == 88]["price"].agg(["count", "mean"])


#  The 88-year-old vehicle group has the highest average listing price at $66,208.33, based on only six listings. This result may reflect the value of particular classic vehicles and should be interpreted cautiously because the group is small.

count        6.000000
mean     66208.333333
Name: price, dtype: float64

In [52]:
# Question 31 — How does average price vary by manufacturing year?
# Let's calculate the average listing price for each vehicle year using groupby().

df.groupby("year")["price"].mean().round(2)

year
1918    16000.00
1922    15000.00
1923    16250.00
1924    15000.00
1926     9247.50
          ...
2018    30036.50
2019    34385.92
2020    37224.42
2021    23236.06
2022     8995.00
Name: price, Length: 98, dtype: float64

In [53]:
# Which manufacturing year has the highest average price

df.groupby("year")["price"].mean().idxmax()

np.int64(1933)

In [55]:
df[df["year"] == 1933]["price"].agg(["count", "mean"])


# Finding: Vehicles manufactured in 1933 have the highest average listing price in the dataset at $66,208.33, based on six listings. This result may reflect classic or collectible vehicles, but the small sample size means it should be interpreted cautiously.

count        6.000000
mean     66208.333333
Name: price, dtype: float64

In [56]:
# Question 33 — Which manufacturers have the highest average listing prices?

df.groupby("manufacturer")["price"].mean().sort_values(ascending=False).head(10).round(2)


#**Finding:** Ferrari has the highest average listing price ($159,773.76), followed by Aston Martin ($109,944.00). This suggests that the listings for these manufacturers are positioned at the premium end of the dataset. Average prices may be influenced by specific models and small sample sizes.

manufacturer
ferrari         159773.76
aston-martin    109944.00
porsche          35447.49
tesla            34943.47
ram              31479.62
alfa-romeo       30238.03
rover            28989.33
jaguar           27255.21
gmc              25911.77
audi             24966.30
Name: price, dtype: float64

In [57]:
# Which manufacturers have the highest average mileage?

df.groupby("manufacturer")["odometer"].mean().sort_values(ascending=False).head(10).round(2)


#**Finding:** Pontiac has the highest average odometer reading among the manufacturers shown, at approximately 131,341.98 miles. Saturn and Mercury follow. These results describe the listings in this sample and may be influenced by vehicle age, model, and sample size.

manufacturer
pontiac            131341.98
saturn             127792.42
mercury            120293.81
harley-davidson    119058.52
toyota             110572.45
honda              103890.38
ford                98831.43
subaru              98266.15
gmc                 97688.91
unknown             96024.73
Name: odometer, dtype: float64

In [58]:
# Compare average prices among the most common manufacturers

top_manufacturers = df["manufacturer"].value_counts().head(10).index

df[df["manufacturer"].isin(top_manufacturers)].groupby("manufacturer")["price"].mean().sort_values(ascending=False).round(2)

# Finding: Among the 10 most common manufacturer labels, RAM has the highest average listing price at $31,479.62. Honda and Nissan have the lowest averages, at $12,911.10 and $12,907.95, respectively. These differences may be influenced by vehicle age, model, mileage, and condition.

manufacturer
ram              31479.62
mercedes-benz    24570.41
jeep             22559.83
ford             22421.89
chevrolet        22410.91
unknown          21987.93
bmw              19999.04
toyota           17204.35
honda            12911.10
nissan           12907.95
Name: price, dtype: float64

In [60]:
df[["price", "year", "odometer", "vehicle_age"]].corr().round(2)


#Price and odometer: Vehicles with higher mileage tend to have lower listing prices.



#Price and year: Newer vehicles tend to have somewhat higher listing prices.



#Price and vehicle age: Older vehicles tend to have somewhat lower listing prices.



#Year and vehicle age: Your correlation is −1.00 because vehicle age is calculated directly from the listing year and manufacturing year. They are mathematically linked, so this perfect negative correlation is expected.



#Odometer and vehicle age: Older vehicles tend to have higher mileage, but the relationship is relatively weak.

             price  year  odometer  vehicle_age
price         1.00  0.28      -0.4        -0.28
year          0.28  1.00      -0.3        -1.00
odometer     -0.40 -0.30       1.0         0.30
vehicle_age  -0.28 -1.00       0.3         1.00

In [61]:
corr_matrix = df[["price", "year", "odometer", "vehicle_age"]].corr()

corr_matrix

#Correlation Analysis — Key Findings

#Vehicle price has a moderate negative correlation with odometer reading (r = −0.403), suggesting that higher-mileage vehicles tend to have lower listing prices.

#Vehicle price has a weak positive correlation with manufacturing year (r = 0.284), suggesting that newer vehicles tend to have higher listing prices.

#Vehicle price has a weak negative correlation with vehicle age (r = −0.284), suggesting that older vehicles tend to have lower listing prices.

#Odometer reading has a weak positive correlation with vehicle age (r = 0.300).

#Manufacturing year and vehicle age have a perfect negative correlation (r = −1.000) because the two variables are mathematically linked.

#These are associations rather than proof of causation. Vehicle model, condition, manufacturer, and other factors can also influence listing prices.

                price      year  odometer  vehicle_age
price        1.000000  0.284273 -0.403268    -0.284316
year         0.284273  1.000000 -0.300247    -1.000000
odometer    -0.403268 -0.300247  1.000000     0.300310
vehicle_age -0.284316 -1.000000  0.300310     1.000000